version: '2'

services:
  redmine:
    build: ./
    image: sameersbn/redmine:5.0.2
    restart: always
    environment:
    - TZ=Asia/Ho_Chi_Minh
    - DB_ADAPTER=mysql2
    - DB_HOST=172.17.0.1
    - DB_PORT=3306
    - DB_USER=redmine
    - DB_PASS=PsezuF1n0Xs5LXoO@
    - DB_NAME=redmine
    # - DB_SSL_MODE=prefer
    - REDMINE_PORT=10445
    - REDMINE_HTTPS=true
    # Defaults for ssl path.  Please read https://github.com/sameersbn/docker-redmine#ssl
    #- SSL_KEY_PATH=/home/redmine/data/certs
    #- SSL_CERTIFICATE_PATH=/home/redmine/data/certs
    #- SSL_DHPARAM_PATH=/home/redmine/data/certs
    - REDMINE_RELATIVE_URL_ROOT=
    - REDMINE_SECRET_TOKEN=

    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15

    - REDMINE_CONCURRENT_UPLOADS=2

    - REDMINE_BACKUP_SCHEDULE=
    - REDMINE_BACKUP_EXPIRY=
    - REDMINE_BACKUP_TIME=

    - SMTP_ENABLED=true
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=2fsoft.info
    - SMTP_HOST=mail.2fsoft.info
    - SMTP_PORT=587
    - SMTP_USER=redmine@2fsoft.info
    - SMTP_PASS=p013gOm!U@le
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_INTERVAL=30

    ports:
    - "10083:80"
    - "10445:443"
    volumes:
    - ./data:/home/redmine/data
    - ./logs:/var/log/redmine
    - ./data/plugins:/home/redmine/redmine/plugins  
